
language: c++

os:
  - linux
  - osx

before_install:
  - git clone -b 2_3 https://github.com/libharu/libharu.git libharu
  - cd libharu
  - ./buildconf.sh --force
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - make
