
language: c

before_install:
  - git clone https://github.com/libharu/libharu.git
  - cd libharu
  - git checkout 2_3
  - ./buildconf.sh --force
  - ./configure
  - make install
  - cd

script:
  - make
